FROM quay.io/soketi/soketi:1.4-16-debian

ENV SOKETI_DEBUG=${DEBUG:-1} \
    DEFAULT_APP_ID=${PUSHER_APP_ID:-some-id} \
    DEFAULT_APP_KEY=${PUSHER_APP_KEY:-app-key} \
    DEFAULT_APP_SECRET=${PUSHER_APP_SECRET:-some-app-secret} \
    PUSHER_HOST=${PUSHER_HOST:-127.0.0.1} \
    PUSHER_PORT=${PUSHER_PORT:-6001} \
    METRICS_SERVER_PORT=${METRICS_SERVER_PORT:-9601} \
    DEFAULT_APP_ENABLE_CLIENT_MESSAGES=${DEFAULT_APP_ENABLE_CLIENT_MESSAGES:-true}

EXPOSE ${SOKETI_PORT:-6001} ${SOKETI_METRICS_SERVER_PORT:-9601}

CMD soketi -host 0.0.0.0 -port ${SOKETI_PORT:-6001} -debug ${SOKETI_DEBUG}
